#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import pandas as pd


# In[14]:


np.__version__, pd.__version__


# In[4]:


df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")


# In[15]:


df


# In[19]:


# df["Make"].value_counts()
# df.groupby("Make")["MSRP"].mean()
# df[df["Make"] == "BMW"]["MSRP"].mean()
# df[df["Year"] >= 2015]["Engine HP"].isna().sum()
df["Engine HP"].mean()


# In[27]:


# df["Engine HP"].fillna(df["Engine HP"].mean()).mean()
# .mean()


# In[34]:


X = df[df["Make"] == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates().to_numpy()


# In[52]:


XTX = np.matmul(X.T, X)
XTX


# In[53]:


X_inv = np.linalg.inv(XTX)

X_inv.sum()


# In[42]:


y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])


# In[48]:


w = X_inv.dot(X.T).dot(y)


# In[49]:


w

